### ISSUE TITLE
Examples for Unit Testing

### ISSUE THREAD

**Issue by tracker1** [martynaskadisa/react-use-redux#2]
Would be nice to see at least a simple example of unit testing this with `jest` or `jest+enzyme`.

aside: love this, hoping it comes to fruition.

**Comment by martynaskadisa** [comment]
Glad you like it! As for testing, I haven't given much of a thought for it yet as hooks are still a proposal.

One thing that comes to mind would be to wrap testing component with a provider in a test case.

```
const store = createMockStore();

const component = mount(
  <StoreContext.Provider value={store}>
    <TestingComponent />
  </StoreContext.Provider>
)
```

**Comment by martynaskadisa** [comment]
You might also be interested in following hooks discussion in `react-redux` repo [here](https://github.com/reduxjs/react-redux/issues/1063)

**Comment by martynaskadisa** [comment]
I'm closing this as there is no point in using this library since `react-redux` supports hooks out the box.
